field: 131af06f-d853-4205-904f-6c835a958650
fieldLayouts:
  4c33e087-7bb1-48ac-ac4d-e0f7dd3f17cf:
    tabs:
      -
        fields:
          039afe33-d5c3-4614-83a0-10c7be623754:
            required: false
            sortOrder: 4
          18f6d14c-b9c2-4582-8eb6-20d1d44bdc5a:
            required: false
            sortOrder: 3
          2420144f-0a2c-48be-9178-a5178f099302:
            required: false
            sortOrder: 2
          b67517d3-0b05-4b8d-8fd6-7b7b6ff7a2cc:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  039afe33-d5c3-4614-83a0-10c7be623754:
    contentColumnType: string
    fieldGroup: null
    handle: imagePlacement
    instructions: ''
    name: 'Image Placement'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  18f6d14c-b9c2-4582-8eb6-20d1d44bdc5a:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:6f85d94b-c535-4e84-802b-33fe7087ab63'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      singleUploadLocationSource: 'volume:4f8ec569-6e1d-4f22-b630-1132bd13bb81'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: ''
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2420144f-0a2c-48be-9178-a5178f099302:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b67517d3-0b05-4b8d-8fd6-7b7b6ff7a2cc:
    contentColumnType: text
    fieldGroup: null
    handle: subhead
    instructions: ''
    name: Subhead
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: question
name: Question
sortOrder: 2
