fieldLayouts:
  a03c157e-7736-4188-b02e-3d908ae6a757:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 73a71b02-a084-4cce-850e-2ab834b84730
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: de9ddb2d-f504-43eb-8c92-5ff7ab72ef33
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 747f7b29-c1ba-4ae0-a18f-6da874d04062
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Donate
        sortOrder: 1
      -
        elements:
          -
            fieldUid: caac16cc-30e8-497f-88b2-ac1a5ccc79c5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: eccb8cfb-a355-4a92-bb67-aebb97ed92f2
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 083bb795-ac2a-4c86-aac3-9f670c828761
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: donate
hasTitleField: false
name: Donate
section: 73888acd-8134-4ecd-9157-c92d260137ae
sortOrder: 1
titleFormat: '{section.name|raw}'
