contentColumnType: string
fieldGroup: 68e682d6-87a3-4206-a8b1-882d516282c9
handle: onwardTeam
instructions: ''
name: 'Onward Team'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - 07742700-6374-4595-9ede-33c0fdfb0aeb
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 3aeb8c76-5c1a-409b-a4b5-979eb325e3ea
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 45fb168c-e0b0-4b98-9b1a-2b6cb51d0de5
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 69a2a3dd-b898-40a1-b810-7e52bd16a941
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 69d9cef3-a2b4-4663-87ee-97a63b511798
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 7cb22f2f-25b8-4ce1-88dd-1180e9339c37
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_onwardteam}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  propagationMethod: all
  selectionLabel: 'Add a person'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
