contentColumnType: string
fieldGroup: d7cadcda-36e7-4698-a430-56f94012c04b
handle: pageBlocks
instructions: ''
name: 'Page Blocks'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pageblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
