contentColumnType: string
fieldGroup: 9591d94f-3f18-46a6-9d97-e03ed9da808f
handle: shareImage
instructions: 'Used when sharing a post or page on social'
name: 'Share Image'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:6f85d94b-c535-4e84-802b-33fe7087ab63'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6f85d94b-c535-4e84-802b-33fe7087ab63'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
