contentColumnType: boolean
fieldGroup: 68e682d6-87a3-4206-a8b1-882d516282c9
handle: showInNav
instructions: 'Show this child page in the site navigation'
name: 'Show in Nav'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
