dateModified: 1602179387
email:
  fromEmail: hello@thisisonward.com
  fromName: Onward
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.sendgrid.net
    password: $SENDGRID_API_KEY
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: apikey
  transportType: craft\mail\transportadapters\Smtp
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
    settings:
      customCss: ''
      customLinks:
        -
          __assoc__:
            -
              - linkLabel
              - 'Site Options'
            -
              - linkUrl
              - /admin/globals/siteOptions
            -
              - adminOnly
              - '1'
      displayDashboardLink: true
      displayDefaultEditSection: true
      displayEditAuthor: true
      displayEditDate: true
      displayGreeting: true
      displayGuideLink: true
      displayLogout: true
      displayRevisionNote: true
      displaySettingsLink: true
      enableMobileMenu: true
      widgets:
        __assoc__:
          -
            - admin-bar_edit-links
            - ''
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of'
      prependSubject: ''
      successFlashMessage: 'Thank you for submitting! If you have another entry, please submit again.'
      toEmail: hello@thisisonward.com
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      confirmationSubject: ''
      confirmationTemplate: ''
      enableConfirmationEmail: ''
      enableDatabase: '1'
      enableTemplateOverwrite: ''
      notificationTemplate: ''
      recaptcha: ''
      recaptchaDataBadge: bottomright
      recaptchaDebug: ''
      recaptchaHideBadge: '1'
      recaptchaSecretKey: $RECAPTCHA_SECRET_KEY
      recaptchaSiteKey: $RECAPTCHA_SITE_KEY
      recaptchaThreshold: '0.5'
      recaptchaTimeout: '30'
      recaptchaVersion: '3'
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: botsLoveTheHoney
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sprout-active:
    edition: standard
    enabled: false
    schemaVersion: 2.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: pro
  live: true
  name: Onward
  schemaVersion: 3.5.13
  timeZone: America/Chicago
