field: 80aede10-a66e-490d-ac5a-469a7283ed27
fieldLayouts:
  42f09ac0-8763-44f0-834c-8752b5b7a958:
    tabs:
      -
        fields:
          302cee28-3841-4c5d-b750-9f30e6a13016:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  302cee28-3841-4c5d-b750-9f30e6a13016:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
